name: Deploy to EC2

on:
  push:
    branches:
#      - develop
      - ci/cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        #run: ./gradlew build
        run: ./gradlew bootJar

      - name: Check build files
        run: |
          ls -l build/libs/
          if [ -f build/libs/AuctionFlow-backend-0.0.1-SNAPSHOT.jar ]; then
            echo "Build file exists."
          else
            echo "Build file does not exist."
            exit 1
          fi

      - name: Upload build files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "build/libs/AuctionFlow-backend-0.0.1-SNAPSHOT.jar"
          #target: "/home/ubuntu/spring-boot-app/"
          target: "spring-boot-app/build/libs"

      - name: Set execute permission on deploy.sh
        run: chmod +x /home/ubuntu/deploy.sh
        # 이 단계는 EC2 인스턴스에서 실행되므로 적절히 SSH 액션을 사용하여 설정해야 함

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            /home/ubuntu/deploy.sh
